[tool.poetry]
name = "skripsi-program"
version = "0.1.0"
description = ""
authors = ["nidduzzi <74892632+nidduzzi@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "skripsi_program"}]

[tool.poetry.dependencies]
python = "3.10.6"
torch = "^2.0.1"
numpy = "^1.24.0"
black = "^23.7.0"
mypy = "^1.4.1"
tqdm = "^4.65.0"
jaxtyping = "^0.2.20"
pandas = "^2.2.2"

[tool.poetry.group.dev.dependencies]
types-tqdm = "^4.65.0.1"
pytest = "^8.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
